#!/usr/bin/env bash
# Generated by agentic-config.
# Run from the project root: ./.agentic-config/install.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PLAN="${SCRIPT_DIR}/install-plan.json"

DRY_RUN=0
FORCE=0
SKIP_PI=0
SKIP_SKILLS=0
SKIP_ENV_CHECK=0

usage() {
  echo "Usage: $0 [--dry-run] [--force] [--skip-pi] [--skip-skills] [--skip-env-check]"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --force) FORCE=1 ;;
    --skip-pi) SKIP_PI=1 ;;
    --skip-skills) SKIP_SKILLS=1 ;;
    --skip-env-check) SKIP_ENV_CHECK=1 ;;
    -h|--help) usage ;;
    *) echo "Unknown option: $1" >&2; usage ;;
  esac
  shift
done

if [[ ! -f "$PLAN" ]]; then
  echo "install-plan.json not found in ${SCRIPT_DIR}" >&2
  exit 1
fi

have() { command -v "$1" >/dev/null 2>&1; }

tool_version() {
  local bin="$1"
  case "$bin" in
    node) node --version 2>/dev/null || true ;;
    pi) pi --version 2>/dev/null | head -1 || true ;;
    jq) jq --version 2>/dev/null || true ;;
    *) "$bin" --version 2>/dev/null | head -1 || true ;;
  esac
}

# Print install docs for a missing binary.
# Args: tool name
print_tool_help() {
  local tool="$1"
  echo ""
  echo "  ${tool} is not installed or not on PATH."
  case "$tool" in
    jq)
      echo "  Docs:    https://jqlang.org/download/"
      echo "  Install: sudo apt-get install -y jq    # Debian/Ubuntu"
      echo "           brew install jq                 # macOS (Homebrew)"
      echo "           sudo dnf install -y jq          # Fedora"
      ;;
    node)
      echo "  Docs:    https://nodejs.org/"
      echo "  Install: https://nodejs.org/en/download/ (LTS installer)"
      echo "           # or with nvm:"
      echo "           curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash"
      ;;
    npx)
      echo "  Docs:    https://docs.npmjs.com/cli/v10/commands/npx"
      echo "  Note:    npx ships with Node.js — install Node.js first."
      echo "  Install: https://nodejs.org/en/download/"
      ;;
    pi)
      echo "  Docs:    https://pi.dev/docs/latest/usage#cli-reference"
      echo "  Install: npm install -g @earendil-works/pi-coding-agent"
      echo "           # then verify: pi --version"
      ;;
    curl)
      echo "  Docs:    https://curl.se/download.html"
      echo "  Install: sudo apt-get install -y curl    # Debian/Ubuntu"
      echo "           brew install curl                 # macOS"
      ;;
    wget)
      echo "  Docs:    https://www.gnu.org/software/wget/"
      echo "  Install: sudo apt-get install -y wget    # Debian/Ubuntu"
      echo "           brew install wget                  # macOS"
      ;;
    git)
      echo "  Docs:    https://git-scm.com/downloads"
      echo "  Install: sudo apt-get install -y git     # Debian/Ubuntu"
      echo "           brew install git                   # macOS"
      ;;
    bash)
      echo "  Note:    bash should be present on POSIX systems."
      ;;
    *)
      echo "  Install: add '${tool}' to your PATH, then re-run ./.agentic-config/install.sh"
      ;;
  esac
}

# Collect binaries required by steps that will actually run (non-optional only).
collect_required_tools() {
  local -n _out=$1
  _out=()
  local seen="|"
  local add_unique
  add_unique() {
    local t="$1"
    [[ "$seen" == *"|${t}|"* ]] && return
    seen="${seen}${t}|"
    _out+=("$t")
  }

  add_unique "jq"

  local step_count i id kind optional requires
  step_count="$(jq '.steps | length' "$PLAN")"
  for ((i = 0; i < step_count; i++)); do
    kind="$(jq -r ".steps[$i].kind" "$PLAN")"
    optional="$(jq -r ".steps[$i].optional // false" "$PLAN")"
    [[ "$optional" == "true" ]] && continue
    if [[ "$kind" == "pi-install" && "$SKIP_PI" -eq 1 ]]; then continue; fi
    if [[ "$kind" == "skills-add" && "$SKIP_SKILLS" -eq 1 ]]; then continue; fi
    requires="$(jq -r '.steps['"$i"'].requires[]?' "$PLAN")"
    while IFS= read -r bin; do
      [[ -n "$bin" ]] && add_unique "$bin"
    done <<< "$requires"
  done
}

run_env_check() {
  local -a required=()
  collect_required_tools required

  echo "Environment check"
  echo "================="
  local missing=0
  local tool ver
  for tool in "${required[@]}"; do
    if have "$tool"; then
      ver="$(tool_version "$tool")"
      if [[ -n "$ver" ]]; then
        echo "[ok]   ${tool} (${ver})"
      else
        echo "[ok]   ${tool}"
      fi
    else
      echo "[MISSING] ${tool}"
      print_tool_help "$tool"
      missing=1
    fi
  done
  echo ""

  if [[ "$missing" -ne 0 ]]; then
    echo "Install the missing tools above, then re-run:" >&2
    echo "  ./.agentic-config/install.sh" >&2
    echo "" >&2
    echo "To skip this check (not recommended): ./.agentic-config/install.sh --skip-env-check" >&2
    return 1
  fi
  echo "All required tools are available."
  echo ""
  return 0
}

command -v jq >/dev/null 2>&1 || {
  echo "jq is required to read install-plan.json" >&2
  print_tool_help "jq"
  exit 1
}

if [[ "$SKIP_ENV_CHECK" -eq 0 ]]; then
  if ! run_env_check; then
    exit 1
  fi
fi

run_step() {
  local id="$1" kind="$2" cmd="$3" requires="$4" optional="$5"

  if [[ "$kind" == "pi-install" && "$SKIP_PI" -eq 1 ]]; then
    echo "[skip] ${id} (--skip-pi)"
    return 0
  fi
  if [[ "$kind" == "skills-add" && "$SKIP_SKILLS" -eq 1 ]]; then
    echo "[skip] ${id} (--skip-skills)"
    return 0
  fi

  local IFS=,
  for bin in $requires; do
    if ! have "$bin"; then
      if [[ "$optional" == "true" || "$optional" == "1" ]]; then
        echo "[skip] ${id} (missing: ${bin}, optional)"
        return 0
      fi
      if [[ "$FORCE" -eq 1 ]]; then
        echo "[warn] ${id} missing ${bin}, continuing (--force)"
      else
        echo "[fail] ${id} requires '${bin}' on PATH" >&2
        print_tool_help "$bin"
        return 1
      fi
    fi
  done

  echo "[run] ${id}: ${cmd}"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    return 0
  fi
  (cd "$PROJECT_ROOT" && eval "$cmd")
}

failed=0
step_count="$(jq '.steps | length' "$PLAN")"

for ((i = 0; i < step_count; i++)); do
  id="$(jq -r ".steps[$i].id" "$PLAN")"
  kind="$(jq -r ".steps[$i].kind" "$PLAN")"
  cmd="$(jq -r ".steps[$i].command" "$PLAN")"
  requires="$(jq -r '.steps['"$i"'].requires | join(",")' "$PLAN")"
  optional="$(jq -r ".steps[$i].optional // false" "$PLAN")"
  if ! run_step "$id" "$kind" "$cmd" "$requires" "$optional"; then
    failed=1
  fi
done

agent="$(jq -r '.skillsAgentFlag // empty' "$PLAN")"
echo ""
if [[ "$failed" -ne 0 ]]; then
  echo "Installer finished with errors." >&2
  exit 1
fi
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "Dry run complete (${step_count} steps)."
else
  echo "Installer finished successfully."
  if [[ -n "$agent" ]]; then
    case "$agent" in
      pi) echo "In Pi, run /reload to pick up new packages and skills." ;;
      cursor) echo "Restart Cursor or reload skills if your harness caches them." ;;
      *) echo "Reload your agent (${agent}) if skills do not appear immediately." ;;
    esac
  fi
fi
