# Generated by agentic-config.
# Run from the project root: .\.agentic-config\install.ps1
param(
  [switch]$DryRun,
  [switch]$Force,
  [switch]$SkipPi,
  [switch]$SkipSkills,
  [switch]$SkipEnvCheck
)

$ErrorActionPreference = "Stop"
$ScriptDir = $PSScriptRoot
$ProjectRoot = Split-Path -Parent $ScriptDir
$PlanPath = Join-Path $ScriptDir "install-plan.json"

$ToolHelp = @{
  jq   = @("Docs:    https://jqlang.org/download/", "Install: winget install jqlang.jq", "         # or: choco install jq")
  node = @("Docs:    https://nodejs.org/", "Install: winget install OpenJS.NodeJS.LTS", "         # or: https://nodejs.org/en/download/")
  npx  = @("Docs:    https://docs.npmjs.com/cli/v10/commands/npx", "Note:    npx ships with Node.js - install Node.js first.")
  pi   = @("Docs:    https://pi.dev/docs/latest/usage#cli-reference", "Install: npm install -g @earendil-works/pi-coding-agent")
  curl = @("Docs:    https://curl.se/download.html", "Install: winget install cURL.cURL")
  wget = @("Docs:    https://www.gnu.org/software/wget/", "Install: winget install JernejSimoncic.Wget")
  git  = @("Docs:    https://git-scm.com/downloads", "Install: winget install Git.Git")
}

function Show-ToolHelp([string]$Tool) {
  Write-Host ""
  Write-Host "  $Tool is not installed or not on PATH."
  if ($ToolHelp.ContainsKey($Tool)) {
    $ToolHelp[$Tool] | ForEach-Object { Write-Host "  $_" }
  } else {
    Write-Host "  Install: add '$Tool' to your PATH, then re-run .\.agentic-config\install.ps1"
  }
}

function Test-Have([string]$Bin) {
  return $null -ne (Get-Command $Bin -ErrorAction SilentlyContinue)
}

function Get-RequiredTools($Plan) {
  $required = [System.Collections.Generic.HashSet[string]]::new()
  foreach ($step in $Plan.steps) {
    if ($step.optional) { continue }
    if ($step.kind -eq "pi-install" -and $SkipPi) { continue }
    if ($step.kind -eq "skills-add" -and $SkipSkills) { continue }
    if ($null -ne $step.requires) {
      foreach ($bin in $step.requires) {
        [void]$required.Add($bin)
      }
    }
  }
  return @($required)
}

function Invoke-EnvCheck($Plan) {
  Write-Host "Environment check"
  Write-Host "================="
  $missing = $false
  foreach ($tool in (Get-RequiredTools $Plan)) {
    if (Test-Have $tool) {
      Write-Host "[ok]   $tool"
    } else {
      Write-Host "[MISSING] $tool"
      Show-ToolHelp $tool
      $missing = $true
    }
  }
  Write-Host ""
  if ($missing) {
    Write-Host "One or more required tools are missing."
    Write-Host "Install the missing tools above, then re-run:"
    Write-Host "  .\.agentic-config\install.ps1"
    Write-Host ""
    Write-Host "To skip this check (not recommended): .\.agentic-config\install.ps1 -SkipEnvCheck"
    exit 1
  }
  Write-Host "All required tools are available."
  Write-Host ""
}

if (-not (Test-Path $PlanPath)) {
  Write-Error "install-plan.json not found in $ScriptDir"
}

$plan = Get-Content $PlanPath -Raw | ConvertFrom-Json

if (-not $SkipEnvCheck) {
  Invoke-EnvCheck $plan
}

$failed = $false

foreach ($step in $plan.steps) {
  if ($step.kind -eq "pi-install" -and $SkipPi) {
    Write-Host "[skip] $($step.id) (-SkipPi)"
    continue
  }
  if ($step.kind -eq "skills-add" -and $SkipSkills) {
    Write-Host "[skip] $($step.id) (-SkipSkills)"
    continue
  }

  $missingReq = @()
  if ($null -ne $step.requires) {
    $missingReq = @($step.requires | Where-Object { -not (Test-Have $_) })
  }
  if ($missingReq.Count -gt 0) {
    if ($step.optional) {
      Write-Host "[skip] $($step.id) (missing prerequisite, optional)"
      continue
    }
    if (-not $Force) {
      foreach ($m in $missingReq) { Show-ToolHelp $m }
      Write-Host -ForegroundColor Red "[fail] $($step.id) requires: $($step.requires -join ', ')"
      exit 1
    }
    Write-Host "[warn] $($step.id) missing prerequisite, continuing (-Force)"
  }

  Write-Host "[run] $($step.id): $($step.command)"
  if (-not $DryRun) {
    Push-Location $ProjectRoot
    try {
      if ($null -ne $step.exe) {
        $args = @()
        if ($null -ne $step.args) { $args = $step.args }
        & $step.exe @args
      } else {
        Invoke-Expression $step.command
      }
    } catch {
      $failed = $true
      Write-Host -ForegroundColor Red "ERROR during step $($step.id): $_"
    } finally {
      Pop-Location
    }
  }
}

if ($failed) { exit 1 }
Write-Host "Installer finished."
